
services:
  auth:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: auth
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
    volumes:
      - ./keycloak_data:/opt/keycloak/data
    command:
      - start-dev
